version: "3.9"
services:
  catalog:
    container_name: catalog
    networks:
      net1:
    build:
        context: ./
        dockerfile: ./catalog/Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/catalog"]
        interval: 15s
        timeout: 7s
        retries: 5
    volumes:
      - .:/code
    ports:
      - "8080:8080"             # accessible using the 8080 port


  simulateddevice:
    container_name: simulateddevice
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    volumes:
      - .:/code
    build:
        context: ./
        dockerfile: ./simulateddevice/Dockerfile

  externalweatherapi:
    container_name: externalweatherapi
    ports:
      - "8070:8080"             # accessible using the 8070 port for testing
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    volumes:
      - .:/code
    environment:
        - OPENWETHERMAPAPIKEY=${OPENWETHERMAPAPIKEY}
    build:
        context: ./
        dockerfile: ./externalweatherapi/Dockerfile

  thinkspeakadaptor:
    container_name: thinkspeakadaptor
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    volumes:
      - .:/code
    build:
        context: ./
        dockerfile: ./thinkspeakadaptor/Dockerfile

  webinterface:
    container_name: webinterface
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    volumes:
      - .:/code
    build:
        context: ./
        dockerfile: ./webinterface/Dockerfile
    ports:
      - "80:8080"             # accessible using the 8080 port

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      net1:
    volumes:
      - node-red:/data

volumes:
  node-red:
  simulateddevice:
  externalweatherapi:
  catalog:
  webinterface:
  thinkspeakadaptor:

networks:
  net1:
    driver: bridge
