version: "3.9"
services:
  catalog:
    container_name: catalog
    networks:
      net1:
    build:
        context: ./
        dockerfile: ./catalog/Dockerfile
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/catalog"]
        interval: 15s
        timeout: 7s
        retries: 5
    ports:
      - "8080:8080"             # accessible using the 8080 port

  simulateddevice:
    container_name: simulateddevice
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    build:
        context: ./
        dockerfile: ./simulateddevice/Dockerfile

  thinkspeakadaptor:
    container_name: thinkspeakadaptor
    networks:
      net1:
    depends_on:
      catalog:
        condition: service_healthy
    links:
        - catalog
    build:
        context: ./
        dockerfile: ./thinkspeakadaptor/Dockerfile

  webpage:
    container_name: webpage
    networks:
      net1:
    build:
        context: ./
        dockerfile: ./webpage/Dockerfile
    ports:
      - "80:8080"             # accessible using the 8080 port

networks:
  net1:
    driver: bridge
