version: "3.9"
services:
  catalog:
    container_name: catalog
    networks:
      net1:
    build:
        context: ./
        dockerfile: ./catalog/Dockerfile
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://catalog:8080/catalog/getBroker | grep uri"]
        interval: 3s
        timeout: 4s
        retries: 5
    volumes:
      - .:/code
    ports:
      - "8080:8080"             # accessible using the 8080 port

  homee:
    container_name: homee
    image: nodered/node-red:latest
    user: root:root             # necessary, otherwise we get 'access denied'
    entrypoint: /data/entrypoint.sh
    command: home1
    depends_on:
      catalog:
        condition: service_healthy
    environment:
      - TZ=Europe/Amsterdam
    networks:
      net1:
    volumes:
      - ./node-red:/data

  web:
    image: nginx:latest
    volumes:
      - ./nginx-templates:/etc/nginx/
    ports:
      - "80:80"
    depends_on:
      catalog:
        condition: service_healthy
    networks:
      net1:

volumes:
  nginx-templates:
  node-red:
  simulateddevice:
  simulateddevice2:
  externalweatherapi:
  catalog:
  webinterface:
  thinkspeakadaptor:

networks:
  net1:
    driver: bridge
